name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit tests
        env:
          WENOWA_TOKEN: ${{ secrets.WENOWA_TOKEN }}
          WENOWA_DEMO_PHONE_NUMBER: ${{ secrets.WENOWA_DEMO_PHONE_NUMBER }}
          WENOWA_DEMO_HEADER: ${{ secrets.WENOWA_DEMO_HEADER }}
          WENOWA_DEMO_MESSAGE: ${{ secrets.WENOWA_DEMO_MESSAGE }}
        run: go test ./...
